export const items =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 16",
      imgSrc: 'https://i5.walmartimages.com/seo/Straight-Talk-iPhone-16-Pro-128GB-Prepaid-Smartphone-Desert-Titanium_2b543cbf-e173-467e-8a71-101c6acd48e1.2c10dec9c25df0a6d8d50e77caea95dc.jpeg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 16 (128 GB) - Blue',
      price: '89999',
    },
    {
      id: 5,
      category: 'laptops',
      title: "Xiaomi [Smartchoice] Notebookpro",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Xiaomi [Smartchoice] Notebookpro ',
      price: '49999',
    },
    {
      id: 7,
      category: 'tablets',
      title: "Xiaomi Pad 6",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Xiaomi Pad 6 | Qualcomm Snapdragon 870 | ',
      price: '29999',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "Apple iPhone 11",
      imgSrc: 'https://cdn.pickr.com.au/wp-content/uploads/2019/09/apple-iphone11.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Apple iPhone 11 (64GB) - Yellow',
      price: '79999',
    },
    {
      id: 6,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro AMOLED",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Storm Grey with Precision Pen 3',
      price: '19999',
    },
    {
      id: 3,
      category: 'mobiles',
      title: "Apple iPhone 13",
      imgSrc: 'https://media.extra.com/s/aurora/100291263_800/Apple-iPhone-13-%2C-5G%2C-256GB%2C-Pink?locale=en-GB,en-*,*',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 13 (128GB) - Pink',
      price: '69999',
    },
    {
      id: 4,
      category: 'laptops',
      title: "Lenovo IdeaPad Slim 5 ",
      imgSrc: 'https://m.media-amazon.com/images/I/61Dw5Z8LzJL._SL1000_.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm) ',
      price: '29999',
    },
    {
      id: 9,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)',
      price: '49999',
    },
    {
      id: 8,
      category: 'laptops',
      title: "Apple MacBook Air Laptop",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
      price: '89999',
    },
    {
      id: 12,
      category: 'mobiles',
      title: "Apple iPhone 15",
      imgSrc: 'https://static.skyassets.com/contentstack/assets/blt143e20b03d72047e/blt421b5c5318c15f83/6501b50cdc211726e3c3158c/Sky_Mobile_PDP1_iPhone15Pro_Black_Titanium-PreOrder.png?imageManager=true&impolicy=resize&width=1000',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 15 (256GB) - Black',
      price: '69999',
    },
    {
      id: 10,
      category: 'tablets',
      title: "Samsung Galaxy Tab A9",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A9 26.69cm (10.5 inch) Display, RAM 6 GB, ROM 128 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)',
      price: '49999',
    },
    {
      id: 11,
      category: 'laptops',
      title: "HP Pavilion Ryzen 5",
      imgSrc: 'https://m.media-amazon.com/images/I/71VlaIUD10L._SL1500_.jpg',
      amazonLink: 'https://www.flipkart.com/hp-pavilion-ryzen-5-hexa-core-amd-r5-5600h-8-gb-512-gb-ssd-windows-10-4-graphics-nvidia-geforce-gtx-1650-144-hz-15-ec2004ax-gaming-laptop/p/itm98c94bbf9bc20',
      description: 'HP pavilion Gaming Ryzen 5, 15-inch/8GB Ram Hd Display, ',
      price: '89999',
    },

  ]